# Travis-CI Build for the OpenRA website
# see travis-ci.org for details

# Same version as the open-ra.org webserver.
language: ruby
rvm:
  - 1.8.7

install:
 - gem install builder kramdown nanoc

script:
 - nanoc compile

after_success:
 - gem install systemu
 - nanoc deploy --target res0l --dry-run

# Only watch the production branch.
branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
